### ISSUE TITLE
IPv6 on FarmBot OS :: Rollbar reports a GenServer exit :)

### ISSUE THREAD

**Issue by jsimmonds2** [nerves-networking/mdns_lite#14] opened 2021-03-04 07:51 UTC
Not sure how to reproduce this one . .  perhaps re-boot a domestic IPv6 router or 3 ? 😉 

![image](https://user-images.githubusercontent.com/1224439/109929900-1aabfc80-7d1b-11eb-981b-6279210bd11f.png)

**Comment by fhunleth** [comment] 2021-03-04 13:19
Thanks for sending the report up. I don't have any theories as to how adding a responder GenServer could have failed, but if I think of anything, I'll let you know.

**Comment by jjcarstens** [comment] 2021-03-04 13:41
This seems like an effect of something bigger. It’s the MdnsLite.ResponderSupervisor that is down here so the call to add a responder child has failed. But there isn’t much indication of why that supervisor is down. And it will shouldn’t be since that is started in the application supervisor.

something else seems to have crashed that supervisor and this is probably a race of adding new IPs before that responder supervisor is back up

**Comment by jsimmonds2** [comment] 2021-03-06 01:16
@jjcarstens here's more context. There's normally an Erlang distribution link to one other node on this ( farmbot_os ) machine.
I just now noticed its address in the Rollbar **Message** heading.  I don't know why `mdns_lite` would be involved in this link.

Here's more detail of the running FarmBot OS host ( latest software ) right now :

![image](https://user-images.githubusercontent.com/1224439/110189947-14319800-7e75-11eb-909a-7a9028492d25.png)

**Comment by jjcarstens** [comment] 2021-03-06 03:49
This isn’t quite enough information to identify MdnsLite as the issue. So far, this seems like an effect of other problems that have happened. With the data above, everything seems to be working. I think we need other error reports or errors/warnings in the logs to identify the cause. Without that, or other reproducible steps, there’s not much to be done with this as there is no indication why the ResponderSupervisor was down.

ipv6 here is just coincidental but was actually ignored as expected

**Comment by jsimmonds2** [comment] 2021-03-06 04:58
> This isn’t quite enough information to identify MdnsLite as the issue

I understand.

> why the ResponderSupervisor was down

Is this part of the `mdns_lite` app or something else ?

> we need other error reports or errors/warnings in the logs

I'll work on that and see whether I can help, as I try to find a reproducer !  ( only the 1 lonely occurrence thus far, a.f.a.i.k. 🙁 )

**Comment by RickCarlino** [comment] 2021-03-08 15:22
Thanks for reporting this @jsimmonds2 . I won't have time to dig deeper for a while, and it appears that the error is recoverable (albeit noisy).

Because FarmBot OS is such a mature codebase (we've been using older versions of the library and I may have made a mistake during upgrades), I have a hunch that the problem may be on our end. My vote would be to close this issue until we are able to produce more data.

**Closed** 2021-03-15 20:07 UTC
